### ISSUE TITLE
Excel 1701

### ISSUE THREAD

**Issue by er77** [OfficeDev/Excel-Add-in-JavaScript-PersistCustomSettings#2]
After installation no new button or task-pane. 

![image](https://user-images.githubusercontent.com/12100294/27996469-07faf63c-64eb-11e7-9e6d-4cb14c70510f.png)

**Comment by Rick-Kirkham** [comment]
Do you get this behavior when you press F5 in Visual Studio? Or are you installing (or sideloading) the add-in? Also, what is the version and build of Office?

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
