### ISSUE TITLE
Persist custom properties

### ISSUE THREAD

**Issue by MhdTlb** [OfficeDev/Excel-Add-in-JavaScript-PersistCustomSettings#3]
I'm unable to set/get custom properties (File => Info => Properties => Advanced Properties => Custom tab)

**Comment by Rick-Kirkham** [comment]
Please provide some details about what your code is doing and exactly what the symptoms are. Are you getting an error message?

**Comment by MhdTlb** [comment]
@Rick-Kirkham  I want to edit custom properties of an Excel document. So after saving my document I can see edited custom property under Custom Properties Tab (File => Info => Properties => Advanced Properties => Custom tab). I tied all possible combination without luck. Is there a way to do so?

**Comment by Rick-Kirkham** [comment]
Custom _properties_ are not accessible programmatically in Excel, only Outlook. The sample in this repo shows you how to create custom _settings_, but these settings are not the same thing as custom properties and there is no way to see the settings in the UI of Excel. For more information, see [Persisting add-in state andsettings](https://dev.office.com/docs/add-ins/develop/persisting-add-in-state-and-settings)
